In [25]:
import pandas as pd
import numpy as np

In [26]:
ds = pd.read_csv("XYZ_Sales.csv")
print(ds)

          Date Product Name  Units Sold  Revenue Region  Discount Offered (%)  \
0   05/01/2026       Laptop          12   144000  North                    10
1   08/01/2026       Tablet          45    22500  South                     5
2   10/01/2026        Phone          30    45000   East                     8
3   12/01/2026       Laptop          18   108000   West                    12
4   15/01/2026        Phone          40    32000  North                     7
5   18/01/2026       Laptop          22    77000  South                    10
6   21/01/2026       Tablet          35    42000   East                     6
7   24/01/2026       Laptop          15    90000   West                    15
8   27/01/2026       Tablet          10    85000  North                     5
9   01/02/2026       Laptop          20   400000  South                     8
10  03/02/2026       Laptop          16   224000   East                    10
11  06/02/2026       Tablet           9    63000   West                     5
12  09/02/2026        Phone          14    70000  North                    12
13  12/02/2026       Laptop          28    84000  South                     7
14  15/02/2026        Phone           6   180000   East                    15
15  18/02/2026       Laptop          11   495000   West                    10
16  21/02/2026       Tablet          50    50000  North                     5
17  24/02/2026       Laptop          26    52000  South                     9
18  27/02/2026       Tablet          24   144000   East                    11
19  02/03/2026       Laptop           8   280000   West                    13

   Salesperson
0         Asha
1         Ravi
2         Neha
3        Kiran
4        Priya
5        Arjun
6        Meera
7         Ravi
8         Asha
9        Kiran
10        Neha
11       Priya
12       Arjun
13       Meera
14        Asha
15        Ravi
16        Neha
17       Kiran
18       Priya
19       Arjun

In [27]:
ds.groupby('Product Name').agg({'Revenue': 'max'})['Revenue'].nlargest(3)

Product Name
Laptop    495000
Phone     180000
Tablet    144000
Name: Revenue, dtype: int64

Q1

In [28]:
ds.sort_values(by="Revenue", ascending=False).head(3)

,Date,Product Name,Units Sold,Revenue,Region,Discount Offered (%),Salesperson
15,18/02/2026,Laptop,11,495000,West,10,Ravi
9,01/02/2026,Laptop,20,400000,South,8,Kiran
19,02/03/2026,Laptop,8,280000,West,13,Arjun

Q2

In [29]:
print( ds.groupby('Product Name')['Units Sold'].sum() )

Product Name
Laptop    176
Phone      90
Tablet    173
Name: Units Sold, dtype: int64

Q3

In [30]:
ds['Total Revenue'] = ds['Revenue'] - ds['Revenue'] * ds['Discount Offered (%)']/100
ds

,Date,Product Name,Units Sold,Revenue,Region,Discount Offered (%),Salesperson,Total Revenue
0,05/01/2026,Laptop,12,144000,North,10,Asha,129600.0
1,08/01/2026,Tablet,45,22500,South,5,Ravi,21375.0
2,10/01/2026,Phone,30,45000,East,8,Neha,41400.0
3,12/01/2026,Laptop,18,108000,West,12,Kiran,95040.0
4,15/01/2026,Phone,40,32000,North,7,Priya,29760.0
5,18/01/2026,Laptop,22,77000,South,10,Arjun,69300.0
6,21/01/2026,Tablet,35,42000,East,6,Meera,39480.0
7,24/01/2026,Laptop,15,90000,West,15,Ravi,76500.0
8,27/01/2026,Tablet,10,85000,North,5,Asha,80750.0
9,01/02/2026,Laptop,20,400000,South,8,Kiran,368000.0
10,03/02/2026,Laptop,16,224000,East,10,Neha,201600.0
11,06/02/2026,Tablet,9,63000,West,5,Priya,59850.0
12,09/02/2026,Phone,14,70000,North,12,Arjun,61600.0
13,12/02/2026,Laptop,28,84000,South,7,Meera,78120.0
14,15/02/2026,Phone,6,180000,East,15,Asha,153000.0
15,18/02/2026,Laptop,11,495000,West,10,Ravi,445500.0
16,21/02/2026,Tablet,50,50000,North,5,Neha,47500.0
17,24/02/2026,Laptop,26,52000,South,9,Kiran,47320.0
18,27/02/2026,Tablet,24,144000,East,11,Priya,128160.0
19,02/03/2026,Laptop,8,280000,West,13,Arjun,243600.0

In [33]:
ds['Total Revenue'] = ds['Revenue'] * (1 - ds['Discount Offered (%)'] / 100)
ds

,Date,Product Name,Units Sold,Revenue,Region,Discount Offered (%),Salesperson,Total Revenue
0,05/01/2026,Laptop,12,144000,North,10,Asha,129600.0
1,08/01/2026,Tablet,45,22500,South,5,Ravi,21375.0
2,10/01/2026,Phone,30,45000,East,8,Neha,41400.0
3,12/01/2026,Laptop,18,108000,West,12,Kiran,95040.0
4,15/01/2026,Phone,40,32000,North,7,Priya,29760.0
5,18/01/2026,Laptop,22,77000,South,10,Arjun,69300.0
6,21/01/2026,Tablet,35,42000,East,6,Meera,39480.0
7,24/01/2026,Laptop,15,90000,West,15,Ravi,76500.0
8,27/01/2026,Tablet,10,85000,North,5,Asha,80750.0
9,01/02/2026,Laptop,20,400000,South,8,Kiran,368000.0
10,03/02/2026,Laptop,16,224000,East,10,Neha,201600.0
11,06/02/2026,Tablet,9,63000,West,5,Priya,59850.0
12,09/02/2026,Phone,14,70000,North,12,Arjun,61600.0
13,12/02/2026,Laptop,28,84000,South,7,Meera,78120.0
14,15/02/2026,Phone,6,180000,East,15,Asha,153000.0
15,18/02/2026,Laptop,11,495000,West,10,Ravi,445500.0
16,21/02/2026,Tablet,50,50000,North,5,Neha,47500.0
17,24/02/2026,Laptop,26,52000,South,9,Kiran,47320.0
18,27/02/2026,Tablet,24,144000,East,11,Priya,128160.0
19,02/03/2026,Laptop,8,280000,West,13,Arjun,243600.0

Q4

In [35]:
ds['Amount Discountd'] = ds['Revenue'] - ds['Total Revenue']
id = ds['Amount Discountd'].idxmax()
ds.loc[id,['Amount Discountd','Salesperson','Total Revenue']]

Amount Discountd     49500.0
Salesperson             Ravi
Total Revenue       445500.0
Name: 15, dtype: object

Q5